"""
PDF Generator module.
Creates a dummy PDF file using reportlab.
"""

from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from datetime import datetime
import os


def generate_pdf(filename="dummy.pdf"):
    """
    Generate a dummy PDF file with sample content.
    
    Args:
        filename: Name of the PDF file to create (default: dummy.pdf)
    
    Returns:
        str: Full path to the generated PDF file
    """
    # Get the directory of this script
    script_dir = os.path.dirname(os.path.abspath(__file__))
    filepath = os.path.join(script_dir, filename)
    
    # Create the PDF
    c = canvas.Canvas(filepath, pagesize=letter)
    width, height = letter
    
    # Title
    c.setFont("Helvetica-Bold", 24)
    c.drawCentredString(width / 2, height - 1.5 * inch, "Demo Report")
    
    # Horizontal line
    c.setLineWidth(2)
    c.line(1 * inch, height - 1.8 * inch, width - 1 * inch, height - 1.8 * inch)
    
    # Content
    c.setFont("Helvetica", 14)
    y_position = height - 2.5 * inch
    
    content_lines = [
        f"User: Test User",
        f"Generated by WhatsApp API Test",
        f"",
        f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"",
        f"This is a sample PDF document created for testing",
        f"the WhatsApp Cloud API document sending feature.",
        f"",
        f"WhatsApp Business Account ID: 1496762318835949",
        f"Phone Number ID: 1057654137421852",
    ]
    
    for line in content_lines:
        c.drawString(1 * inch, y_position, line)
        y_position -= 0.4 * inch
    
    # Footer
    c.setFont("Helvetica-Oblique", 10)
    c.drawCentredString(width / 2, 0.75 * inch, "Generated using Meta WhatsApp Cloud API Demo")
    
    # Save the PDF
    c.save()
    
    print(f"[PDF] Generated PDF: {filepath}")
    return filepath


if __name__ == "__main__":
    # Test PDF generation
    pdf_path = generate_pdf()
    print(f"PDF created at: {pdf_path}")
